### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by ghost** [Amarinder1/Project3-Backend#8]
@Amarinder1 I've looked into your issue and was able to deploy your app here: https://radiant-shelf-42779.herokuapp.com/home

There are definitely several ways to solve each problem. Here is how I solved it:
`connection.js`
```
if(process.env.NODE_ENV == 'production'){
  mongoose.connect(process.env.MONGODB_URI)
} else {
  mongoose.connect('mongodb://localhost/Project3-Backend')
}
```
Then
`package.json`
```
"scripts": {
    "start": "node index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  }
```
Then in the CLI
```bash
$ heroku create project-name
$ git push heroku master
$ heroku addons:create mongolab
$ heroku config:get MONGODB_URI
```
Maybe you should consider deleting your Heroku app, and creating a new one with the same name, because your current app has a bunch of configurations which might take you some time to fix.

Good luck!

**Comment by Amarinder1** [comment]
Thank You!
